# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122vGtL-esaZqErF0GvFca0CfHkp-7wnG

Erika Dommer

Machine Learning

DSA 507

August 30th 2025

## Assignment 1

Using the cars.csv dataset, we want to study the vehicle's fuel consumption (mpg) and the impact of variables such as horsepower (hp), vehicle weight (wt), and cylinders (cyl).

* Explore the relationship between variables.
* Train a model.
* Review the assumptions of the model.
* Make predictions for the top 10% most fuel-efficient cars. Ensure that only significant variables remain in your model.
* How many possible models can be constructed considering all the variables in the original dataframe, i.e., consider models with 1 variable, 2 variables, etc.?
"""

datacars=pd.read_csv("cars.csv")
datacars.head(10)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.formula.api as smf
import statsmodels.api as sm
import statsmodels.stats.api as sms
from statsmodels.compat import lzip

datacars=pd.read_csv("cars.csv")
datacars.columns = ['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
datacars.head(10)

#we want to study the vehicle's fuel consumption (mpg) and the impact of variables such as horsepower (hp), vehicle weight (wt), and cylinders (cyl).
selected_columns= datacars[['mpg','wt','hp','cyl']]

#creating pairpllot using on selected columns:'mpg','wt','hp','cyl'
sns.pairplot(selected_columns)

"""***Exploring the relationship between variables via scatterplot matrix***

*   Mg(dependent variable) vs Wt(indepenent variable): as wieght increases, mpg
decreases.
*    Mg(dependent variable) vs hp(indepenent variable): as hp increases, mpg decreases
*   Mg(dependent variable) vs cyl(indepenent variable): as cyl size increase, ,mpg decreases

***Multicollinearity observed***
*   For the relationship between the the depedent variables (wt vs hp,wt vs cyl and hp vs cyl) we notice a upward slope pattern I as one variable increases the other also increases.) This means there is a positive correlation








"""

selected_columns.corr()

"""Observation for Correlation results



*   Mpg vs (all depedent variables) shows strong negative correlation, where  wt, hp and cyl (independenlty) are higher then mpg is lower.

 We observe again the in the strong postive correlation between the independent variables.

*   wt vs hp = 0.6587
*   wt vs cyl = 0.7825
*   hp vs cyl = 0.8324

To address the issue with **multicollinearity**, will use Regularization, Lasson Regression. This is am attempt to simplfy the model. Will shrink some coefficients to zero.
"""

import pandas as pd
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

datacars = pd.read_csv("cars.csv")
selected_columns = datacars[['mpg', 'wt', 'hp', 'cyl']]

# Define depetent and indepedent variables
X = selected_columns[['wt', 'hp', 'cyl']]
y = selected_columns['mpg']

#creating test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#scaling  regularized model to ensure its is reliable
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#applying lasson regression
lasso = Lasso(alpha=0.1)  # smaller alpha for Lasso
lasso.fit(X_train_scaled, y_train)

lasso_preds = lasso.predict(X_test_scaled)
print("Lasso R²:", r2_score(y_test, lasso_preds))

"""Lasso R^2 explains there is an 81.4% variance based on wt,ho and cyl. Meaning the model captured most of the fuel effeiency patterns in the data."""

import numpy as np
mse = mean_squared_error(y_test, lasso_preds)
rmse = np.sqrt(mse)
print("Lasso RMSE:", rmse)



"""Lasso RMSE predicts than on average, the models mpg predictions are off by 2.73 mpg.

The above code was used to **train the model**. By providing input features x_train_scajed and target_values Y, the lasso algorithm then learned the relationship between those features and traget by optimizing the co-efficents.
"""

#including MSE
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, lasso_preds)
print("Lasso MSE:", mse)

#baseline MSE
from sklearn.metrics import mean_squared_error
mean_pred = [y_train.mean()] * len(y_test)
baseline_mse = mean_squared_error(y_test, mean_pred)
print("Baseline MSE:", baseline_mse)

"""The Lasso Model reduces the prediction error by over 80% based of the **MSE and baselinr MSE comparision.**

\text{Improvement} = \frac{40.11 - 7.43}{40.11} \approx 81.5\%

The above confirmed that the model captures key patterns in the data.
"""

import statsmodels.formula.api as smf

model_ols = smf.ols(formula="mpg ~ wt + hp + cyl", data=selected_columns).fit()
print(model_ols.summary())

"""In the aboved code, the model was **trained** by using the Ordinary Least Sqaures (OLS) regression. The model learned the relationship between mpg and the predictors by analzying patterns in the data. This will also us to use predictions from model_ols.predict() in next steps of analysis.

***Assumptions***

Linearity:
-  High R-sqaured(0.843) and Prob (F-statistic): 2.18e-11 suggest the model fits the data well and supports linearitt assumption.

Normaility of residuals:
- The Omnibus (5.519) and Jarque-Bera (3.368) tests have p-values > 0.05, suggesting that residuals are not significantly non-normal

Independence of Residuals
- The Durbin-Watson statistic is 2.264, which is very close to 2—this indicates that residuals are not autocorrelated. Indepedence assumption holds

Multicollinearity
- The standard errors and t-values suggest that  may not be significant (p = 0.397)
"""

model_ols.resid #checking residuals

from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.tools.tools import add_constant
from statsmodels.compat import lzip

name = ["Lagrange Multiplier", "p-value", "f-value", "f p-value"]
test = het_breuschpagan(model_ols.resid, model_ols.model.exog)
print(lzip(name, test))

"""Notes on Breusch-Pagan test: both p-values are above 0.05, we can reject the null value hypothesis. This models residuals appear to have equal variance.



"""

#Idenitfy top 10% most fuel efficient cars
top_10_percent = datacars.nlargest(int(len(datacars) * 0.10), 'mpg')

#Predictions for 10& most fuel efficient cars
predictions = model_ols.predict(top_10_percent)
top_10_percent['predicted_mpg'] = predictions

print(top_10_percent[['model', 'mpg', 'predicted_mpg']])

"""**The top 10% most fuel-efficient cars**: Toyota Corolla, Fiat 128 and Honda Civic."""

#All possible models that can be constructed considering all the variables in the original dataframe
import itertools
#predictor variable names
predictors = ['cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
#count all non-empty combinations
total_models = sum(1 for r in range(1, len(predictors)+1) for combo in itertools.combinations(predictors, r))

print("Total possible models:", total_models)

"""Total possible models that can be constructed considereing all the variable in the orginal datafram is **1023.**"""